<?php

namespace AppBundle\Repository;

/**
 * AddToCartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddToCartRepository extends \Doctrine\ORM\EntityRepository
{
}
