<?php

namespace AppBundle\Repository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllLimit($limit=5)
    {
        return $this->findBy(array(), array('date' => 'DESC'),$limit);
    }
    public function findAllLimitClean()
    {
        return $this->findBy(array(), array('date' => 'DESC'),5);
    }
    public function findAllDesc()
    {
        return $this->findBy(array(), array('date' => 'DESC'));
    }
}
