<?php

namespace AppBundle\Repository;

/**
 * NoticeInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticeInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
